//
// Original source - secretgen-controller - Copyright 2024 The Carvel Authors.
// Re-organized and updated as - templated-secret-controller - (C) 2025 starstreak.dev
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SecretTemplateListerExpansion allows custom methods to be added to
// SecretTemplateLister.
type SecretTemplateListerExpansion interface{}

// SecretTemplateNamespaceListerExpansion allows custom methods to be added to
// SecretTemplateNamespaceLister.
type SecretTemplateNamespaceListerExpansion interface{}
