// Based on work by Carvel - that work Copyright 2024 The Carvel Authors.
// Re-organized by starstreak.dev - that work Copyright 2025 starstreak.dev
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/drae/templated-secret-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SecretTemplates returns a SecretTemplateInformer.
	SecretTemplates() SecretTemplateInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// SecretTemplates returns a SecretTemplateInformer.
func (v *version) SecretTemplates() SecretTemplateInformer {
	return &secretTemplateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
