//
// Original source - secretgen-controller - Copyright 2024 The Carvel Authors.
// Re-organized and updated as - templated-secret-controller - (C) 2025 starstreak.dev
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated typed clients.
package v1alpha1
