//
// Original source - secretgen-controller - Copyright 2024 The Carvel Authors.
// Re-organized and updated as - templated-secret-controller - (C) 2025 starstreak.dev
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/drae/templated-secret-controller/pkg/client/clientset/versioned/typed/templatedsecret/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTemplatedsecretV1alpha1 struct {
	*testing.Fake
}

func (c *FakeTemplatedsecretV1alpha1) SecretTemplates(namespace string) v1alpha1.SecretTemplateInterface {
	return newFakeSecretTemplates(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTemplatedsecretV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
