name: Lint Helm Charts

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read # Needed for checkout and helm operations

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-testing (lint)
        run: ct lint --validate-maintainers=false --check-version-increment=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
